[package]
name = "autara-oracle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
entrypoint = []

[dependencies]

autara-lib.workspace = true
arch_program.workspace = true
borsh.workspace = true
bytemuck.workspace = true
